version: '3.4'

services:

  # First the AspNet Core app
 testredis:
   ## Get the image to use and set the container name
    image: ${DOCKER_REGISTRY-}testredis
    build:
      context: .
      dockerfile: TestRedis/Dockerfile
      
    # State a dependancy on Redis working
    depends_on:
      - "redis_image"
      
    # Set access ports for localhost on the left
    
    # Configure a link to Redis
    links:
      - "redis_image"
    # The Application needs a connection string for Redis, this just needs to be the Redis Service name as defined below
    # Pass it in as an Environmental Variable
    environment:
      - RedisConnection=redis_image
      
 redis_image:
    # Pull the image from Docker Hub
    image: redis

    # Give the container a name (any name you want)
    container_name: redis.cache
      
